### PR TITLE
Breaking: amd to es6 modules

### PR DESCRIPTION
**Pull request by hzoo**
Conversion automated via https://github.com/jonbretman/amd-to-as6

- `npx amd-to-es6 --dir Component --out Component` for all the folders
- had to use sourceType module for eslint due to using es modules
- had to upgrade webpack/instanbul to handle modules correctly as well

### CODE REVIEW

**Comment by hzoo** [comment]
I can wait for 6.1.1 and do a 7 after @YellowPanda11 merges

**Comment by YellowPanda11** [comment]
@hzoo thanks, let's do that

**Comment by mikesherov** [comment]
If we're going to break, we should es6ify.

**Comment by mikesherov** [comment]
And switch to babel blacklist instead of whitelist in our apps.

**Comment by hzoo** [comment]
How about in another PR?

**Comment by kaicataldo** [comment]
Indentation can be fixed by ESLint's autofix once we upgrade ESLint to 4.x

**Pull request merged**
