### PR TITLE
util/uploadValidator refactor

### PR DESCRIPTION
**Pull request by kaicataldo**
It was pointed out that the function could just be inlined - figured I could make this clearer for the next person. https://github.com/behance/BeFF/pull/148#discussion_r71495987

### CODE REVIEW

**Comment by designjockey** [comment]
👍

**Comment by designjockey** [comment]
This doesn't affect tests?

**Comment by kaicataldo** [comment]
Nope, this is truly a refactor - literally inlining a function. No behavioral change whatsoever!

**Comment by mmase** [comment]
LGTM

**Pull request merged**
