### PR TITLE
Build: remove bower and requirejs

### PR DESCRIPTION
**Pull request by mikesherov**

### CODE REVIEW

**Comment by nemtsov** [comment]
Btw, this closes: https://github.com/adobe-community/issues/issues/10445  ( :) )

**Comment by designjockey** [comment]
Travis failure:
```
ERROR in ./test/specs/ractive/Model.js
Module not found: Error: Cannot resolve module 'Ractive' in /home/travis/build/behance/BeFF/test/specs/ractive
 @ ./test/specs/ractive/Model.js 1:0-137:2
[32m11 09 2016 03:36:15.442:INFO [karma]: [39mKarma v1.1.2 server started at http://localhost:9876/
[32m11 09 2016 03:36:15.444:INFO [launcher]: [39mLaunching browser PhantomJS with unlimited concurrency
[32m11 09 2016 03:36:15.476:INFO [launcher]: [39mStarting browser PhantomJS
[32m11 09 2016 03:36:15.814:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: [39mConnected on socket /#YxjTdEWiCtB1IfI6AAAA with id 68895236
[31mPhantomJS 2.1.1 (Linux 0.0.0) ERROR[39m
  Error: Cannot find module "Ractive"
  at undefined:2
```

**Comment by designjockey** [comment]
👍  once Travis passes

**Comment by nemtsov** [comment]
👍

**Comment by agaripian** [comment]
👍

**Pull request merged**
